SET IDENTITY_INSERT [dbo].[Security] ON;
GO

MERGE INTO [dbo].[Security] AS Target
USING (VALUES
  (1, 1, N'MMM', N'3M Co.'),
  (2, 1, N'ACE', N'ACE Limited'),
  (3, 1, N'ABT', N'Abbott Laboratories'),
  (4, 1, N'ANF', N'Abercrombie & Fitch Company A'),
  (5, 1, N'ACN', N'Accenture'),
  (6, 2, N'ADBE', N'Adobe Systems Inc'),
  (7, 1, N'AMD', N'Advanced Micro Devices'),
  (8, 1, N'AES', N'AES Corp'),
  (9, 1, N'AET', N'Aetna Inc'),
  (10, 1, N'AFL', N'AFLAC Inc'),
  (11, 1, N'A', N'Agilent Technologies Inc'),
  (12, 1, N'GAS', N'AGL Resources Inc.'),
  (13, 1, N'APD', N'Air Products & Chemicals Inc'),
  (14, 1, N'ARG', N'Airgas Inc'),
  (15, 2, N'AKAM', N'Akamai Technologies Inc'),
  (16, 1, N'AA', N'Alcoa Inc'),
  (17, 2, N'ALXN', N'Alexion Pharmaceuticals'),
  (18, 1, N'ATI', N'Allegheny Technologies Inc'),
  (19, 1, N'AGN', N'Allergan Inc'),
  (20, 1, N'ALL', N'Allstate Corp'),
  (21, 2, N'ALTR', N'Altera Corp'),
  (22, 1, N'MO', N'Altria Group Inc'),
  (23, 2, N'AMZN', N'Amazon.com Inc'),
  (24, 1, N'AEE', N'Ameren Corp'),
  (25, 1, N'AEP', N'American Electric Power'),
  (26, 1, N'AXP', N'American Express Co'),
  (27, 1, N'AIG', N'American Intl Group Inc'),
  (28, 1, N'AMT', N'American Tower Corp A'),
  (29, 1, N'AMP', N'Ameriprise Financial'),
  (30, 1, N'ABC', N'AmerisourceBergen Corp'),
  (31, 2, N'AMGN', N'Amgen Inc'),
  (32, 2, N'APH', N'Amphenol Corp A'),
  (33, 1, N'APC', N'Anadarko Petroleum Corp'),
  (34, 1, N'ADI', N'Analog Devices Inc'),
  (35, 1, N'AON', N'Aon plc'),
  (36, 1, N'APA', N'Apache Corporation'),
  (37, 1, N'AIV', N'Apartment Investment & Mgmt'),
  (38, 2, N'APOL', N'Apollo Group Inc'),
  (39, 2, N'AAPL', N'Apple Inc.'),
  (40, 2, N'AMAT', N'Applied Materials Inc'),
  (41, 1, N'ADM', N'Archer-Daniels-Midland Co'),
  (42, 1, N'AIZ', N'Assurant Inc'),
  (43, 1, N'T', N'AT&T Inc'),
  (44, 2, N'ADSK', N'Autodesk Inc'),
  (45, 2, N'ADP', N'Automatic Data Processing'),
  (46, 1, N'AN', N'AutoNation Inc'),
  (47, 1, N'AZO', N'AutoZone Inc'),
  (48, 1, N'AVB', N'AvalonBay Communities, Inc.'),
  (49, 1, N'AVY', N'Avery Dennison Corp'),
  (50, 1, N'AVP', N'Avon Products'),
  (51, 1, N'BHI', N'Baker Hughes Inc'),
  (52, 1, N'BLL', N'Ball Corp'),
  (53, 1, N'BAC', N'Bank of America Corp'),
  (54, 1, N'BK', N'The Bank of New York Mellon Corp.'),
  (55, 1, N'BCR', N'Bard (C.R.) Inc.'),
  (56, 1, N'BAX', N'Baxter International Inc.'),
  (57, 1, N'BBT', N'BB&T Corporation'),
  (58, 1, N'BEAM', N'Beam Inc.'),
  (59, 1, N'BDX', N'Becton Dickinson'),
  (60, 2, N'BBBY', N'Bed Bath & Beyond'),
  (61, 1, N'BMS', N'Bemis Company'),
  (62, 1, N'BRK.B', N'Berkshire Hathaway'),
  (63, 1, N'BBY', N'Best Buy Co. Inc.'),
  (64, 1, N'BIG', N'Big Lots Inc.'),
  (65, 2, N'BIIB', N'BIOGEN IDEC Inc.'),
  (66, 1, N'BLK', N'BlackRock'),
  (67, 1, N'HRB', N'Block H&R'),
  (68, 1, N'BMC', N'BMC Software'),
  (69, 1, N'BA', N'Boeing Company'),
  (70, 1, N'BWA', N'BorgWarner'),
  (71, 1, N'BXP', N'Boston Properties'),
  (72, 1, N'BSX', N'Boston Scientific'),
  (73, 1, N'BMY', N'Bristol-Myers Squibb'),
  (74, 2, N'BRCM', N'Broadcom Corporation'),
  (75, 1, N'BF.B', N'Brown-Forman Corporation'),
  (76, 2, N'CHRW', N'C. H. Robinson Worldwide'),
  (77, 2, N'CA', N'CA, Inc.'),
  (78, 2, N'CVC', N'Cablevision Systems Corp.'),
  (79, 1, N'COG', N'Cabot Oil & Gas'),
  (80, 1, N'CAM', N'Cameron International Corp.'),
  (81, 1, N'CPB', N'Campbell Soup'),
  (82, 1, N'COF', N'Capital One Financial'),
  (83, 1, N'CAH', N'Cardinal Health Inc.'),
  (84, 1, N'CFN', N'Carefusion'),
  (85, 1, N'KMX', N'Carmax Inc'),
  (86, 1, N'CCL', N'Carnival Corp.'),
  (87, 1, N'CAT', N'Caterpillar Inc.'),
  (88, 1, N'CBG', N'CBRE Group'),
  (89, 1, N'CBS', N'CBS Corp.'),
  (90, 2, N'CELG', N'Celgene Corp.'),
  (91, 1, N'CNP', N'CenterPoint Energy'),
  (92, 1, N'CTL', N'CenturyLink Inc'),
  (93, 2, N'CERN', N'Cerner'),
  (94, 1, N'CF', N'CF Industries Holdings Inc'),
  (95, 1, N'SCHW', N'Charles Schwab'),
  (96, 1, N'CHK', N'Chesapeake Energy'),
  (97, 1, N'CVX', N'Chevron Corp.'),
  (98, 2, N'CMG', N'Chipotle Mexican Grill'),
  (99, 1, N'CB', N'Chubb Corp.'),
  (100, 1, N'CI', N'CIGNA Corp.'),
  (101, 2, N'CINF', N'Cincinnati Financial'),
  (102, 2, N'CTAS', N'Cintas Corporation'),
  (103, 2, N'CSCO', N'Cisco Systems'),
  (104, 1, N'C', N'Citigroup Inc.'),
  (105, 2, N'CTXS', N'Citrix Systems'),
  (106, 1, N'CLF', N'Cliffs Natural Resources'),
  (107, 1, N'CLX', N'Clorox Co.'),
  (108, 2, N'CME', N'CME Group Inc.'),
  (109, 1, N'CMS', N'CMS Energy'),
  (110, 1, N'COH', N'Coach Inc.'),
  (111, 1, N'KO', N'Coca Cola Co.'),
  (112, 1, N'CCE', N'Coca-Cola Enterprises'),
  (113, 2, N'CTSH', N'Cognizant Technology Solutions'),
  (114, 1, N'CL', N'Colgate-Palmolive'),
  (115, 2, N'CMCSA', N'Comcast Corp.'),
  (116, 1, N'CMA', N'Comerica Inc.'),
  (117, 1, N'CSC', N'Computer Sciences Corp.'),
  (118, 1, N'CAG', N'ConAgra Foods Inc.'),
  (119, 1, N'COP', N'ConocoPhillips'),
  (120, 1, N'CNX', N'CONSOL Energy Inc.'),
  (121, 1, N'ED', N'Consolidated Edison'),
  (122, 1, N'STZ', N'Constellation Brands'),
  (123, 1, N'CBE', N'Cooper Industries'),
  (124, 1, N'GLW', N'Corning Inc.'),
  (125, 2, N'COST', N'Costco Co.'),
  (126, 1, N'CVH', N'Coventry Health Care Inc.'),
  (127, 1, N'COV', N'Covidien plc'),
  (128, 1, N'CCI', N'Crown Castle International Corp.'),
  (129, 1, N'CSX', N'CSX Corp.'),
  (130, 1, N'CMI', N'Cummins Inc.'),
  (131, 1, N'CVS', N'CVS Caremark Corp.'),
  (132, 1, N'DHI', N'D. R. Horton'),
  (133, 1, N'DHR', N'Danaher Corp.'),
  (134, 1, N'DRI', N'Darden Restaurants'),
  (135, 1, N'DVA', N'DaVita Inc.'),
  (136, 1, N'DF', N'Dean Foods'),
  (137, 1, N'DE', N'Deere & Co.'),
  (138, 2, N'DELL', N'Dell Inc.'),
  (139, 1, N'DNR', N'Denbury Resources Inc.'),
  (140, 1, N'XRAY', N'Dentsply International'),
  (141, 1, N'DVN', N'Devon Energy Corp.'),
  (142, 1, N'DV', N'DeVry, Inc.'),
  (143, 1, N'DO', N'Diamond Offshore Drilling'),
  (144, 2, N'DTV', N'DirecTV'),
  (145, 1, N'DFS', N'Discover Financial Services'),
  (146, 2, N'DISCA', N'Discovery Communications'),
  (147, 2, N'DLTR', N'Dollar Tree'),
  (148, 1, N'D', N'Dominion Resources'),
  (149, 1, N'RRD', N'Donnelley (R.R.) & Sons'),
  (150, 1, N'DOV', N'Dover Corp.'),
  (151, 1, N'DOW', N'Dow Chemical'),
  (152, 1, N'DPS', N'Dr Pepper Snapple Group'),
  (153, 1, N'DTE', N'DTE Energy Co.'),
  (154, 1, N'DD', N'Du Pont (E.I.)'),
  (155, 1, N'DUK', N'Duke Energy'),
  (156, 1, N'DNB', N'Dun & Bradstreet'),
  (157, 2, N'ETFC', N'E-Trade'),
  (158, 1, N'EMN', N'Eastman Chemical'),
  (159, 1, N'ETN', N'Eaton Corp.'),
  (160, 2, N'EBAY', N'eBay Inc.'),
  (161, 1, N'ECL', N'Ecolab Inc.'),
  (162, 1, N'EIX', N'Edison Int''l'),
  (163, 1, N'EW', N'Edwards Lifesciences'),
  (164, 2, N'EA', N'Electronic Arts'),
  (165, 1, N'EMC', N'EMC Corp.'),
  (166, 1, N'EMR', N'Emerson Electric'),
  (167, 1, N'ESV', N'Ensco plc'),
  (168, 1, N'ETR', N'Entergy Corp.'),
  (169, 1, N'EOG', N'EOG Resources'),
  (170, 1, N'EQT', N'EQT Corporation'),
  (171, 1, N'EFX', N'Equifax Inc.'),
  (172, 1, N'EQR', N'Equity Residential'),
  (173, 1, N'EL', N'Estee Lauder Cos.'),
  (174, 1, N'EXC', N'Exelon Corp.'),
  (175, 2, N'EXPE', N'Expedia Inc.'),
  (176, 2, N'EXPD', N'Expeditors Int''l'),
  (177, 2, N'ESRX', N'Express Scripts'),
  (178, 1, N'XOM', N'Exxon Mobil Corp.'),
  (179, 2, N'FFIV', N'F5 Networks'),
  (180, 1, N'FDO', N'Family Dollar Stores'),
  (181, 2, N'FAST', N'Fastenal Co'),
  (182, 1, N'FII', N'Federated Investors Inc.'),
  (183, 1, N'FDX', N'FedEx Corporation'),
  (184, 1, N'FIS', N'Fidelity National Information Services'),
  (185, 2, N'FITB', N'Fifth Third Bancorp'),
  (186, 1, N'FHN', N'First Horizon National'),
  (187, 1, N'FSLR', N'First Solar Inc'),
  (188, 1, N'FE', N'FirstEnergy Corp'),
  (189, 2, N'FISV', N'Fiserv Inc'),
  (190, 1, N'FLIR', N'FLIR Systems'),
  (191, 1, N'FLS', N'Flowserve Corporation'),
  (192, 1, N'FLR', N'Fluor Corp.'),
  (193, 1, N'FMC', N'FMC Corporation'),
  (194, 1, N'FTI', N'FMC Technologies Inc.'),
  (195, 1, N'F', N'Ford Motor'),
  (196, 1, N'FRX', N'Forest Laboratories'),
  (197, 1, N'FOSL', N'Fossil, Inc.'),
  (198, 1, N'BEN', N'Franklin Resources'),
  (199, 1, N'FCX', N'Freeport-McMoran Cp & Gld'),
  (200, 1, N'FTR', N'Frontier Communications'),
  (201, 1, N'GME', N'GameStop Corp.'),
  (202, 1, N'GCI', N'Gannett Co.'),
  (203, 1, N'GPS', N'Gap (The)'),
  (204, 1, N'GD', N'General Dynamics'),
  (205, 1, N'GE', N'General Electric'),
  (206, 1, N'GIS', N'General Mills'),
  (207, 1, N'GPC', N'Genuine Parts'),
  (208, 1, N'GNW', N'Genworth Financial Inc.'),
  (209, 2, N'GILD', N'Gilead Sciences'),
  (210, 1, N'GS', N'Goldman Sachs Group'),
  (211, 1, N'GT', N'Goodyear Tire & Rubber'),
  (212, 2, N'GOOG', N'Google Inc.'),
  (213, 1, N'GWW', N'Grainger (W.W.) Inc.'),
  (214, 1, N'HAL', N'Halliburton Co.'),
  (215, 1, N'HOG', N'Harley-Davidson'),
  (216, 1, N'HAR', N'Harman Int''l Industries'),
  (217, 1, N'HRS', N'Harris Corporation'),
  (218, 1, N'HIG', N'Hartford Financial Svc.Gp.'),
  (219, 1, N'HAS', N'Hasbro Inc.'),
  (220, 1, N'HCP', N'HCP Inc.'),
  (221, 1, N'HCN', N'Health Care REIT'),
  (222, 1, N'HNZ', N'Heinz (H.J.)'),
  (223, 1, N'HP', N'Helmerich & Payne'),
  (224, 1, N'HES', N'Hess Corporation'),
  (225, 1, N'HPQ', N'Hewlett-Packard'),
  (226, 1, N'HD', N'Home Depot'),
  (227, 1, N'HON', N'Honeywell Int''l Inc.'),
  (228, 1, N'HRL', N'Hormel Foods Corp.'),
  (229, 1, N'HSP', N'Hospira Inc.'),
  (230, 1, N'HST', N'Host Hotels & Resorts'),
  (231, 2, N'HCBK', N'Hudson City Bancorp'),
  (232, 1, N'HUM', N'Humana Inc.'),
  (233, 2, N'HBAN', N'Huntington Bancshares'),
  (234, 1, N'ITW', N'Illinois Tool Works'),
  (235, 1, N'IR', N'Ingersoll-Rand PLC'),
  (236, 1, N'TEG', N'Integrys Energy Group Inc.'),
  (237, 2, N'INTC', N'Intel Corp.'),
  (238, 1, N'ICE', N'IntercontinentalExchange Inc.'),
  (239, 1, N'IBM', N'International Bus. Machines'),
  (240, 1, N'IFF', N'International Flav/Frag'),
  (241, 1, N'IGT', N'International Game Technology'),
  (242, 1, N'IP', N'International Paper'),
  (243, 1, N'IPG', N'Interpublic Group'),
  (244, 2, N'INTU', N'Intuit Inc.'),
  (245, 2, N'ISRG', N'Intuitive Surgical Inc.'),
  (246, 1, N'IVZ', N'Invesco Ltd.'),
  (247, 1, N'IRM', N'Iron Mountain Incorporated'),
  (248, 1, N'JBL', N'Jabil Circuit'),
  (249, 1, N'JEC', N'Jacobs Engineering Group'),
  (250, 2, N'JDSU', N'JDS Uniphase Corp.'),
  (251, 1, N'JNJ', N'Johnson & Johnson'),
  (252, 1, N'JCI', N'Johnson Controls'),
  (253, 2, N'JOY', N'Joy Global Inc.'),
  (254, 1, N'JPM', N'JPMorgan Chase & Co.'),
  (255, 2, N'JNPR', N'Juniper Networks'),
  (256, 1, N'K', N'Kellogg Co.'),
  (257, 1, N'KEY', N'KeyCorp'),
  (258, 1, N'KMB', N'Kimberly-Clark'),
  (259, 1, N'KIM', N'Kimco Realty'),
  (260, 1, N'KMI', N'Kinder Morgan'),
  (261, 2, N'KLAC', N'KLA-Tencor Corp.'),
  (262, 1, N'KSS', N'Kohl''s Corp.'),
  (263, 1, N'KRFTV', N'Kraft Foods Group Inc.'),
  (264, 1, N'KFT', N'Kraft Foods Inc-A'),
  (265, 1, N'KR', N'Kroger Co.'),
  (266, 1, N'LLL', N'L-3 Communications Holdings'),
  (267, 1, N'LH', N'Laboratory Corp. of America Holding'),
  (268, 2, N'LRCX', N'Lam Research'),
  (269, 1, N'LM', N'Legg Mason'),
  (270, 1, N'LEG', N'Leggett & Platt'),
  (271, 1, N'LEN', N'Lennar Corp.'),
  (272, 1, N'LUK', N'Leucadia National Corp.'),
  (273, 1, N'LXK', N'Lexmark Int''l Inc'),
  (274, 2, N'LIFE', N'Life Technologies'),
  (275, 1, N'LLY', N'Lilly (Eli) & Co.'),
  (276, 1, N'LTD', N'Limited Brands Inc.'),
  (277, 1, N'LNC', N'Lincoln National'),
  (278, 2, N'LLTC', N'Linear Technology Corp.'),
  (279, 1, N'LMT', N'Lockheed Martin Corp.'),
  (280, 1, N'L', N'Loews Corp.'),
  (281, 1, N'LO', N'Lorillard Inc.'),
  (282, 1, N'LOW', N'Lowe''s Cos.'),
  (283, 1, N'LSI', N'LSI Corporation'),
  (284, 1, N'LYB', N'LyondellBasell'),
  (285, 1, N'MTB', N'M&T Bank Corp.'),
  (286, 1, N'M', N'Macy''s Inc.'),
  (287, 1, N'MRO', N'Marathon Oil Corp.'),
  (288, 1, N'MPC', N'Marathon Petroleum'),
  (289, 1, N'MAR', N'Marriott Int''l.'),
  (290, 1, N'MMC', N'Marsh & McLennan'),
  (291, 1, N'MAS', N'Masco Corp.'),
  (292, 1, N'MA', N'Mastercard Inc.'),
  (293, 1, N'MAT', N'Mattel Inc.'),
  (294, 1, N'MKC', N'McCormick & Co.'),
  (295, 1, N'MCD', N'McDonald''s Corp.'),
  (296, 1, N'MHP', N'McGraw-Hill'),
  (297, 1, N'MCK', N'McKesson Corp.'),
  (298, 1, N'MJN', N'Mead Johnson'),
  (299, 1, N'MWV', N'MeadWestvaco Corporation'),
  (300, 1, N'MDT', N'Medtronic Inc.'),
  (301, 1, N'MRK', N'Merck & Co.'),
  (302, 1, N'MET', N'MetLife Inc.'),
  (303, 1, N'PCS', N'MetroPCS Communications Inc.'),
  (304, 2, N'MCHP', N'Microchip Technology'),
  (305, 2, N'MU', N'Micron Technology'),
  (306, 2, N'MSFT', N'Microsoft Corp.'),
  (307, 2, N'MOLX', N'Molex Inc.'),
  (308, 1, N'TAP', N'Molson Coors Brewing Company'),
  (309, 1, N'MON', N'Monsanto Co.'),
  (310, 2, N'MNST', N'Monster Beverage'),
  (311, 1, N'MCO', N'Moody''s Corp'),
  (312, 1, N'MS', N'Morgan Stanley'),
  (313, 1, N'MOS', N'The Mosaic Company'),
  (314, 1, N'MSI', N'Motorola Solutions Inc.'),
  (315, 1, N'MUR', N'Murphy Oil'),
  (316, 2, N'MYL', N'Mylan Inc.'),
  (317, 1, N'NBR', N'Nabors Industries Ltd.'),
  (318, 2, N'NDAQ', N'NASDAQ OMX Group'),
  (319, 1, N'NOV', N'National Oilwell Varco Inc.'),
  (320, 2, N'NTAP', N'NetApp'),
  (321, 2, N'NFLX', N'NetFlix Inc.'),
  (322, 1, N'NWL', N'Newell Rubbermaid Co.'),
  (323, 1, N'NFX', N'Newfield Exploration Co'),
  (324, 1, N'NEM', N'Newmont Mining Corp. (Hldg. Co.)'),
  (325, 2, N'NWSA', N'News Corporation'),
  (326, 1, N'NEE', N'NextEra Energy Resources'),
  (327, 1, N'NKE', N'NIKE Inc.'),
  (328, 1, N'NI', N'NiSource Inc.'),
  (329, 1, N'NE', N'Noble Corp'),
  (330, 1, N'NBL', N'Noble Energy Inc'),
  (331, 1, N'JWN', N'Nordstrom'),
  (332, 1, N'NSC', N'Norfolk Southern Corp.'),
  (333, 2, N'NTRS', N'Northern Trust Corp.'),
  (334, 1, N'NOC', N'Northrop Grumman Corp.'),
  (335, 1, N'NU', N'Northeast Utilities'),
  (336, 1, N'NRG', N'NRG Energy'),
  (337, 1, N'NUE', N'Nucor Corp.'),
  (338, 2, N'NVDA', N'Nvidia Corporation'),
  (339, 1, N'NYX', N'NYSE Euronext'),
  (340, 2, N'ORLY', N'O''Reilly Automotive'),
  (341, 1, N'OXY', N'Occidental Petroleum'),
  (342, 1, N'OMC', N'Omnicom Group'),
  (343, 1, N'OKE', N'ONEOK'),
  (344, 2, N'ORCL', N'Oracle Corp.'),
  (345, 1, N'OI', N'Owens-Illinois Inc'),
  (346, 2, N'PCAR', N'PACCAR Inc.'),
  (347, 1, N'PLL', N'Pall Corp.'),
  (348, 1, N'PH', N'Parker-Hannifin'),
  (349, 2, N'PDCO', N'Patterson Companies'),
  (350, 2, N'PAYX', N'Paychex Inc.'),
  (351, 1, N'BTU', N'Peabody Energy'),
  (352, 1, N'JCP', N'Penney (J.C.)'),
  (353, 2, N'PBCT', N'People''s United Bank'),
  (354, 1, N'POM', N'Pepco Holdings Inc.'),
  (355, 1, N'PEP', N'PepsiCo Inc.'),
  (356, 1, N'PKI', N'PerkinElmer'),
  (357, 1, N'PRGO', N'Perrigo'),
  (358, 1, N'PFE', N'Pfizer Inc.'),
  (359, 1, N'PCG', N'PG&E Corp.'),
  (360, 1, N'PM', N'Philip Morris International'),
  (361, 1, N'PSX', N'Phillips 66'),
  (362, 1, N'PNW', N'Pinnacle West Capital'),
  (363, 1, N'PXD', N'Pioneer Natural Resources'),
  (364, 1, N'PBI', N'Pitney-Bowes'),
  (365, 1, N'PCL', N'Plum Creek Timber Co.'),
  (366, 1, N'PNC', N'PNC Financial Services'),
  (367, 1, N'RL', N'Polo Ralph Lauren Corp.'),
  (368, 1, N'PPG', N'PPG Industries'),
  (369, 1, N'PPL', N'PPL Corp.'),
  (370, 1, N'PX', N'Praxair Inc.'),
  (371, 1, N'PCP', N'Precision Castparts'),
  (372, 2, N'PCLN', N'Priceline.com Inc'),
  (373, 1, N'PFG', N'Principal Financial Group'),
  (374, 1, N'PG', N'Procter & Gamble'),
  (375, 1, N'PGR', N'Progressive Corp.'),
  (376, 1, N'PLD', N'ProLogis'),
  (377, 1, N'PRU', N'Prudential Financial'),
  (378, 1, N'PEG', N'Public Serv. Enterprise Inc.'),
  (379, 1, N'PSA', N'Public Storage'),
  (380, 1, N'PHM', N'Pulte Homes Inc.'),
  (381, 1, N'QEP', N'QEP Resources'),
  (382, 1, N'PWR', N'Quanta Services Inc.'),
  (383, 2, N'QCOM', N'QUALCOMM Inc.'),
  (384, 1, N'DGX', N'Quest Diagnostics'),
  (385, 1, N'RRC', N'Range Resources Corp.'),
  (386, 1, N'RTN', N'Raytheon Co.'),
  (387, 1, N'RHT', N'Red Hat Inc.'),
  (388, 1, N'RF', N'Regions Financial Corp.'),
  (389, 1, N'RSG', N'Republic Services Inc'),
  (390, 1, N'RAI', N'Reynolds American Inc.'),
  (391, 1, N'RHI', N'Robert Half International'),
  (392, 1, N'ROK', N'Rockwell Automation Inc.'),
  (393, 1, N'COL', N'Rockwell Collins'),
  (394, 1, N'ROP', N'Roper Industries'),
  (395, 2, N'ROST', N'Ross Stores Inc.'),
  (396, 1, N'RDC', N'Rowan Cos.'),
  (397, 1, N'R', N'Ryder System'),
  (398, 1, N'SWY', N'Safeway Inc.'),
  (399, 1, N'SAI', N'SAIC'),
  (400, 1, N'CRM', N'Salesforce.com'),
  (401, 2, N'SNDK', N'SanDisk Corporation'),
  (402, 1, N'SCG', N'SCANA Corp'),
  (403, 1, N'SLB', N'Schlumberger Ltd.'),
  (404, 1, N'SNI', N'Scripps Networks Interactive Inc.'),
  (405, 2, N'STX', N'Seagate Technology'),
  (406, 1, N'SEE', N'Sealed Air Corp.(New)'),
  (407, 1, N'SRE', N'Sempra Energy'),
  (408, 1, N'SHW', N'Sherwin-Williams'),
  (409, 2, N'SIAL', N'Sigma-Aldrich'),
  (410, 1, N'SPG', N'Simon Property Group Inc'),
  (411, 1, N'SLM', N'SLM Corporation'),
  (412, 1, N'SJM', N'Smucker (J.M.)'),
  (413, 1, N'SNA', N'Snap-On Inc.'),
  (414, 1, N'SO', N'Southern Co.'),
  (415, 1, N'LUV', N'Southwest Airlines'),
  (416, 1, N'SWN', N'Southwestern Energy'),
  (417, 1, N'SE', N'Spectra Energy Corp.'),
  (418, 1, N'S', N'Sprint Nextel Corp.'),
  (419, 1, N'STJ', N'St Jude Medical'),
  (420, 1, N'SWK', N'Stanley Black & Decker'),
  (421, 2, N'SPLS', N'Staples Inc.'),
  (422, 2, N'SBUX', N'Starbucks Corp.'),
  (423, 1, N'HOT', N'Starwood Hotels & Resorts'),
  (424, 1, N'STT', N'State Street Corp.'),
  (425, 1, N'SRCL', N'Stericycle Inc'),
  (426, 1, N'SYK', N'Stryker Corp.'),
  (427, 1, N'SUN', N'Sunoco Inc.'),
  (428, 1, N'STI', N'SunTrust Banks'),
  (429, 2, N'SYMC', N'Symantec Corp.'),
  (430, 1, N'SYY', N'Sysco Corp.'),
  (431, 2, N'TROW', N'T. Rowe Price Group'),
  (432, 1, N'TGT', N'Target Corp.'),
  (433, 1, N'TEL', N'TE Connectivity Ltd.'),
  (434, 1, N'TE', N'TECO Energy'),
  (435, 1, N'THC', N'Tenet Healthcare Corp.'),
  (436, 1, N'TDC', N'Teradata Corp.'),
  (437, 1, N'TER', N'Teradyne Inc.'),
  (438, 1, N'TSO', N'Tesoro Petroleum Co.'),
  (439, 2, N'TXN', N'Texas Instruments'),
  (440, 1, N'TXT', N'Textron Inc.'),
  (441, 1, N'HSY', N'The Hershey Company'),
  (442, 1, N'TRV', N'The Travelers Companies Inc.'),
  (443, 1, N'TMO', N'Thermo Fisher Scientific'),
  (444, 1, N'TIF', N'Tiffany & Co.'),
  (445, 1, N'TWX', N'Time Warner Inc.'),
  (446, 1, N'TWC', N'Time Warner Cable Inc.'),
  (447, 1, N'TIE', N'Titanium Metals Corp'),
  (448, 1, N'TJX', N'TJX Companies Inc.'),
  (449, 1, N'TMK', N'Torchmark Corp.'),
  (450, 1, N'TSS', N'Total System Services'),
  (451, 2, N'TRIP', N'TripAdvisor'),
  (452, 1, N'TSN', N'Tyson Foods'),
  (453, 1, N'TYC', N'Tyco International'),
  (454, 1, N'USB', N'U.S. Bancorp'),
  (455, 1, N'UNP', N'Union Pacific'),
  (456, 1, N'UNH', N'United Health Group Inc.'),
  (457, 1, N'UPS', N'United Parcel Service'),
  (458, 1, N'X', N'United States Steel Corp.'),
  (459, 1, N'UTX', N'United Technologies'),
  (460, 1, N'UNM', N'Unum Group'),
  (461, 2, N'URBN', N'Urban Outfitters'),
  (462, 1, N'VFC', N'V.F. Corp.'),
  (463, 1, N'VLO', N'Valero Energy'),
  (464, 1, N'VAR', N'Varian Medical Systems'),
  (465, 1, N'VTR', N'Ventas Inc'),
  (466, 2, N'VRSN', N'Verisign Inc.'),
  (467, 1, N'VZ', N'Verizon Communications'),
  (468, 2, N'VIAB', N'Viacom Inc.'),
  (469, 1, N'V', N'Visa Inc.'),
  (470, 1, N'VNO', N'Vornado Realty Trust'),
  (471, 1, N'VMC', N'Vulcan Materials'),
  (472, 1, N'WMT', N'Wal-Mart Stores'),
  (473, 1, N'WAG', N'Walgreen Co.'),
  (474, 1, N'DIS', N'Walt Disney Co.'),
  (475, 1, N'WPO', N'Washington Post Co B'),
  (476, 1, N'WM', N'Waste Management Inc.'),
  (477, 1, N'WAT', N'Waters Corporation'),
  (478, 1, N'WPI', N'Watson Pharmaceuticals'),
  (479, 1, N'WLP', N'WellPoint Inc.'),
  (480, 1, N'WFC', N'Wells Fargo'),
  (481, 1, N'WDC', N'Western Digital'),
  (482, 1, N'WU', N'Western Union Co'),
  (483, 1, N'WY', N'Weyerhaeuser Corp.'),
  (484, 1, N'WHR', N'Whirlpool Corp.'),
  (485, 2, N'WFM', N'Whole Foods Market'),
  (486, 1, N'WMB', N'Williams Cos.'),
  (487, 1, N'WIN', N'Windstream Corporation'),
  (488, 1, N'WEC', N'Wisconsin Energy Corporation'),
  (489, 1, N'WPX', N'WPX Energy, Inc.'),
  (490, 1, N'WYN', N'Wyndham Worldwide'),
  (491, 2, N'WYNN', N'Wynn Resorts Ltd'),
  (492, 1, N'XEL', N'Xcel Energy Inc'),
  (493, 1, N'XRX', N'Xerox Corp.'),
  (494, 2, N'XLNX', N'Xilinx Inc'),
  (495, 1, N'XL', N'XL Capital'),
  (496, 1, N'XYL', N'Xylem Inc.'),
  (497, 2, N'YHOO', N'Yahoo Inc.'),
  (498, 1, N'YUM', N'Yum! Brands Inc'),
  (499, 1, N'ZMH', N'Zimmer Holdings'),
  (500, 2, N'ZION', N'Zions Bancorp')
)
AS Source ([SecurityID], [ExchangeID], [Ticker], [Name])
ON Target.[SecurityID] = Source.[SecurityID]
-- update matched rows
WHEN MATCHED THEN
UPDATE SET [ExchangeID] = Source.[ExchangeID], [Type] = 1, [Ticker] = Source.[Ticker], [Name] = Source.[Name]
-- insert new rows
WHEN NOT MATCHED BY TARGET THEN
INSERT ([SecurityID], [ExchangeID], [Type], [Ticker], [Name])
VALUES ([SecurityID], [ExchangeID], 1, [Ticker], [Name])
-- delete rows that are in the target but not the source
WHEN NOT MATCHED BY SOURCE THEN 
DELETE;
GO

SET IDENTITY_INSERT [dbo].[Security] OFF;
GO
